import type { Metadata } from 'next';
import { Toaster } from '@/components/ui/sonner';
import RootProvider from '@/providers/root';
import { ClerkProvider } from '@clerk/nextjs';
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { extractRouterConfig } from 'uploadthing/server';
import { ourFileRouter } from './api/uploadthing/core';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <RootProvider>
        <html lang="en" className="size-full">
          <body
            className="size-full antialiased"
          >
            <Toaster richColors theme="light" />
            <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
            {children}
          </body>
        </html>
      </RootProvider>
    </ClerkProvider>
  );
}
